-- MySQL Script generated by MySQL Workbench
-- Fri May 11 21:13:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AstraSoftware
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AstraSoftware
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AstraSoftware` DEFAULT CHARACTER SET utf8 ;
USE `AstraSoftware` ;

-- -----------------------------------------------------
-- Table `AstraSoftware`.`CADCLIN1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AstraSoftware`.`CADCLIN1` (
  `COD` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(50) NOT NULL COMMENT 'NOME DO CLIENTE',
  `PESSOA` VARCHAR(1) NOT NULL COMMENT 'DISPONIBILIZAR APENSA \"J\" OU \"F\" PARA PESSOA FISICA OU JURIDICA',
  `DOCIND` VARCHAR(20) NOT NULL COMMENT 'CNPJ OU CPF',
  `TEL` VARCHAR(16) NOT NULL,
  `END` VARCHAR(50) NOT NULL,
  `CIDADE` VARCHAR(45) NOT NULL,
  `ESTADO` VARCHAR(45) NOT NULL,
  `CEP` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`COD`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AstraSoftware`.`CADFORNEC1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AstraSoftware`.`CADFORNEC1` (
  `COD` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NULL,
  `PESSOA` VARCHAR(1) NULL,
  `DOCIND` VARCHAR(20) NULL,
  `TEL` VARCHAR(16) NULL,
  `END` VARCHAR(45) NULL,
  `CIDADE` VARCHAR(45) NULL,
  `ESTADO` VARCHAR(45) NULL,
  `CEP` VARCHAR(9) NULL,
  PRIMARY KEY (`COD`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AstraSoftware`.`CADUSER1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AstraSoftware`.`CADUSER1` (
  `COD` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(50) NOT NULL COMMENT 'NOME DO CLIENTE',
  `DOCIND` VARCHAR(14) NOT NULL COMMENT 'CNPJ OU CPF',
  `TEL` VARCHAR(16) NOT NULL,
  `PERMITION` TINYINT NOT NULL DEFAULT 0,
  `EMAIL` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`COD`, `DOCIND`),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC),
  UNIQUE INDEX `DOCIND_UNIQUE` (`DOCIND` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AstraSoftware`.`CADPROD1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AstraSoftware`.`CADPROD1` (
  `COD` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `DESC` TEXT(100) NOT NULL,
  `SALDO` INT NOT NULL,
  `PREÇO` FLOAT NOT NULL,
  PRIMARY KEY (`COD`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AstraSoftware`.`CABPEDVEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AstraSoftware`.`CABPEDVEN` (
  `COD` INT NOT NULL AUTO_INCREMENT,
  `CADCLIN1_COD` INT NOT NULL,
  `CODCLIENTE` INT NOT NULL,
  `NOMECLI` VARCHAR(45) NOT NULL,
  `TOTAL_PED` FLOAT NOT NULL,
  `CABPEDcol` VARCHAR(45) NOT NULL,
  `DATA_PED` DATE NOT NULL,
  PRIMARY KEY (`COD`),
  INDEX `fk_CABPED_CADCLIN1_idx` (`CADCLIN1_COD` ASC),
  CONSTRAINT `fk_CABPED_CADCLIN1`
    FOREIGN KEY (`CADCLIN1_COD`)
    REFERENCES `AstraSoftware`.`CADCLIN1` (`COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AstraSoftware`.`ITEPEDVEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AstraSoftware`.`ITEPEDVEN` (
  `CABPED_COD` INT NOT NULL,
  `CADPROD1_COD` INT NOT NULL,
  `QTD` INT NULL,
  `PREC` FLOAT NULL,
  `TOTAL` FLOAT NULL,
  INDEX `fk_ITEPED_CABPED1_idx` (`CABPED_COD` ASC),
  INDEX `fk_ITEPED_CADPROD11_idx` (`CADPROD1_COD` ASC),
  CONSTRAINT `fk_ITEPED_CABPED1`
    FOREIGN KEY (`CABPED_COD`)
    REFERENCES `AstraSoftware`.`CABPEDVEN` (`COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEPED_CADPROD11`
    FOREIGN KEY (`CADPROD1_COD`)
    REFERENCES `AstraSoftware`.`CADPROD1` (`COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AstraSoftware`.`CONREC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AstraSoftware`.`CONREC` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESC` TEXT(100) NOT NULL,
  `DATVENCIM` DATE NOT NULL,
  `VALOR` FLOAT NOT NULL,
  `RECEBIDO` TINYINT NOT NULL DEFAULT 0,
  `CABPEDVEN_COD` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_CONREC_CABPEDVEN1_idx` (`CABPEDVEN_COD` ASC),
  CONSTRAINT `fk_CONREC_CABPEDVEN1`
    FOREIGN KEY (`CABPEDVEN_COD`)
    REFERENCES `AstraSoftware`.`CABPEDVEN` (`COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AstraSoftware`.`CABPEDCOMP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AstraSoftware`.`CABPEDCOMP` (
  `COD` INT NOT NULL AUTO_INCREMENT,
  `CODCLIENTE` INT NOT NULL,
  `NOMECLI` VARCHAR(45) NOT NULL,
  `TOTAL_PED` FLOAT NULL,
  `CADFORNEC1_COD` INT NOT NULL,
  PRIMARY KEY (`COD`),
  INDEX `fk_CABPEDCOMP_CADFORNEC11_idx` (`CADFORNEC1_COD` ASC),
  CONSTRAINT `fk_CABPEDCOMP_CADFORNEC11`
    FOREIGN KEY (`CADFORNEC1_COD`)
    REFERENCES `AstraSoftware`.`CADFORNEC1` (`COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AstraSoftware`.`CONPAGAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AstraSoftware`.`CONPAGAR` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESC` TEXT(100) CHARACTER SET 'latin2' COLLATE 'latin2_croatian_ci' NOT NULL,
  `DATVENCIM` DATE NOT NULL,
  `VALOR` FLOAT NOT NULL,
  `PAGO` TINYINT NULL DEFAULT 0,
  `DATPAGAMENTO` DATE NULL,
  `CABPEDCOMP_COD` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_CONPAGAR_CABPEDCOMP1_idx` (`CABPEDCOMP_COD` ASC),
  CONSTRAINT `fk_CONPAGAR_CABPEDCOMP1`
    FOREIGN KEY (`CABPEDCOMP_COD`)
    REFERENCES `AstraSoftware`.`CABPEDCOMP` (`COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AstraSoftware`.`ITEPEDCOMP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AstraSoftware`.`ITEPEDCOMP` (
  `QTD` INT NULL,
  `PREC` FLOAT NULL,
  `TOTAL` FLOAT NULL,
  `CABPEDCOMP_COD` INT NOT NULL,
  `CADPROD1_COD` INT NOT NULL,
  INDEX `fk_ITEPEDCOMP_CABPEDCOMP1_idx` (`CABPEDCOMP_COD` ASC),
  INDEX `fk_ITEPEDCOMP_CADPROD11_idx` (`CADPROD1_COD` ASC),
  CONSTRAINT `fk_ITEPEDCOMP_CABPEDCOMP1`
    FOREIGN KEY (`CABPEDCOMP_COD`)
    REFERENCES `AstraSoftware`.`CABPEDCOMP` (`COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEPEDCOMP_CADPROD11`
    FOREIGN KEY (`CADPROD1_COD`)
    REFERENCES `AstraSoftware`.`CADPROD1` (`COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
